from django.shortcuts import render
import random
from django.contrib.auth.decorators import login_required

@login_required
def fun_home(request):
    return render(request, 'funzone/home.html')


def love_calculator(request):
    percentage = None

    if request.method == "POST":
        name1 = request.POST.get('name1')
        name2 = request.POST.get('name2')
        percentage = random.randint(50, 100)

    return render(request, 'funzone/love_calculator.html', {
        'percentage': percentage
    })


def message_generator(request):
    messages = [
        "You make my heart feel brand new 🆕❤️",
            "You're the melody my heart keeps singing 🎶❤️",
    "You make every moment feel like a fairytale 🏰✨",
    "You're my favorite sunrise and sunset 🌅🌇",
    "You're the reason my heart feels so full 💖",
    "You make ordinary moments extraordinary 🌟",
    "You're the love story I always wanted 📖💕",
    "You're my happy thought that never ends 💭😊",
    "You make my world brighter than fireworks 🎆",
    "You're the calm in my crazy storm ⛈️🌈",
    "You're my forever favorite person forever 💕",
    "You make my heart feel brand new every day 🆕❤️",
    "You're the dream I never want to wake up from 💤✨",
    "You're the missing piece I didn't know I needed 🧩💖",
    "You make my soul feel lighter than air 🎈",
    "You're my favorite chapter in life's book 📚❤️",
    "You're the warmth that melts all my worries away 🔥💫",
    "You make every day Valentine's with you 💝",
    "You're the smile that starts in my heart 😊💓",
    "You're my personal shooting star 🌠💖",
    "You make my life a beautiful melody 🎵❤️",
    "You're the love that makes everything make sense 💕✨",
    "You're my favorite feeling in the whole world 🌎💖",
    "You make my heart dance in the rain ☔💃",
    "You're the peace in my chaos 🌪️🕊️",
    "You're my always and forever love 💍❤️",
    "You make my soul feel like it's flying 🦅💫",
    "You're the best surprise life ever gave me 🎁💖",
    "You're the home my heart was searching for 🏠❤️",
    "You make every moment golden ⭐✨",
    "You're the love that heals everything 💊💕",
    "You're my favorite adventure partner 🗺️❤️",
    "You make my world sparkle with joy ✨😄",
    "You're the answer to every love song 🎤💖",
    "You're the calm sea to my wild waves 🌊☀️",
    "You make my heart bloom like spring flowers 🌸💓",
    "You're the love that time can't fade ⏰💕",
    "You're my favorite memory in the making 📸❤️",
    "You make my soul feel truly alive 💖🌟",
    "You're the magic in my ordinary days 🪄✨",
    "You're the love that makes me believe in destiny 💫💕",
    "You're my favorite fairytale come true 🏰❤️",
    "You make my heart feel limitless ♾️💖",
    "You're the perfect harmony to my melody 🎵💕",
    "You're the love that colors my world 🎨🌈",
    "You make every day feel like a celebration 🎉❤️",
    "You're the dream I never knew I had 💭💖",
    "You're the love that makes everything worthwhile 💕✨",
    "You're my favorite miracle every single day 🙏❤️",
    "You make my soul feel complete 🌟💖",
    "You're the love story I'll tell forever 📖💕"    
    "You're my favorite kind of magic 🔮✨",
    "You make my heart do the happy dance 🕺💃",
    "You're the rainbow to my cloudy day 🌈☁️",
    "You're my favorite notification sound 📱💖",
    "You make my soul do backflips 🤸‍♀️💫",
    "You're my perfect cup of tea ☕❤️",
    "You're the spark in my firework 🎆✨",
    "You make my worries float away 🎈💕",
    "You're my favorite playlist 🎵❤️",
    "You're the warmth in my winter ❄️🔥",
    "You make my smile bigger than the moon 🌝😊",
    "You're my lucky star ⭐💖",
    "You're the best view in my life 🌄❤️",
    "You make my heart go doki-doki 💓💓",
    "You're my favorite emoji 💕😍",
    "You're the sugar to my spice 🍬🌶️",
    "You make my days 100x better 💯💫",
    "You're my personal sunshine dealer ☀️💛",
    "You're the best WiFi signal I ever got 📶❤️",
    "You make my heart do cartwheels 🤸‍♂️💕",
    "You're my favorite kind of trouble 😈💖",
    "You're the mint to my chocolate 🍃🍫",
    "You make my world less scary 👻💕",
    "You're my favorite app update 📲❤️",
    "You're the cool to my breeze 🌬️💖",
    "You make my heart do the cha-cha 🕺💃",
    "You're my favorite glitch in the matrix 🖥️💕",
    "You're the jelly to my peanut butter 🥜🍇",
    "You make my soul do jazz hands ✋🎷",
    "You're my favorite algorithm 📊❤️",
    "You're the snap to my crackle pop 🍚💥",
    "You make my days Insta-worthy 📸💫",
    "You're my personal serotonin boost 🧠💖",
    "You're the best plot twist ever 📖❤️",
    "You make my heart go vroom-vroom 🚗💕",
    "You're my favorite glitch in the system 💾💖",
    "You're the marshmallow to my hot cocoa 🍫☁️",
    "You make my soul do TikTok dances 📱💃",
    "You're my favorite software update 💻❤️",
    "You're the crunch to my cereal 🥣💖",
    "You make my heart do the Macarena 💃🕺",
    "You're my favorite math equation ➕❤️",
    "You're the sprinkles to my ice cream 🍨✨",
    "You make my days go brrrrr 💨💕",
    "You're my personal dopamine dealer 🧪💖",
    "You're the best error 404 I ever got ❌❤️",
    "You make my heart do the floss 🦷💃",
    "You're my favorite browser cookie 🍪💕",
    "You're the chill to my vibes 🎧💖",
    "You make my soul do the worm 🐛💫",
    "You're my favorite cloud storage ☁️❤️",
    "You're the pop to my bubble wrap 🎈💥",
    "You make my heart go beep-boop 🤖💕",
    "You're my favorite loading screen ⏳💖",
    "You're the crunch to my autumn leaves 🍂💫",
    "You make my days buffer-free 📺❤️",
    "You're my personal coffee machine ☕💖",
    "You're the best software bug ever 🐛❤️",
    "You make my heart do the robot 🤖💃",
    "You're my favorite password 🔑💕",
    "You're the jam to my doughnut 🍩🍓",
    "You make my soul do the moonwalk 🌙🕺",
    "You're my favorite spam email 📧💖",
    "You're the twist to my lemonade 🍋🌀",
    "You make my heart go ping-pong 🏓💕",
    "You're my favorite pixel 🎮❤️",
    "You're the crunch to my snow ❄️💫",
    "You make my days high-definition 📺💖",
    "You're my personal energy drink ⚡❤️",
    "You're the best autocorrect ever ✏️💕",
    "You make my heart do the hokey pokey 🤪💃",
    "You're my favorite bookmark 🔖💖",
    "You're the fizz to my soda 🥤💥",
    "You make my soul do the Carlton 🕺💫",
    "You're my favorite cache memory 💾❤️",
    "You're the crunch to my potato chips 🥔💖",
    "You make my heart go zig-zag ⚡💕",
    "You're my favorite pop-up ad 📢❤️",
    "You're the cream to my coffee ☕🥛",
    "You make my days 4K ultra HD 🎬💫",
    "You're my personal pizza delivery 🍕💖",
    "You're the best glitch in my code 💻❤️",
    "You make my heart do the running man 🏃‍♂️💕",
    "You're my favorite browser history 🌐💖",
    "You're the crunch to my toast 🍞💫",
    "You make my soul do the flamenco 💃🔥",
    "You're my favorite hard drive 💽❤️",
    "You're the fizz to my bath bomb 🛁✨",
    "You make my heart go tap dance 👞💕",
    "You're my favorite spam folder 📁💖",
    "You're the cream to my Oreo 🍪🥛",
    "You make my days buffering... in a good way ⏳❤️",
    "You're my personal snack machine 🍫💫",
    "You're the best typo I ever made ⌨️💕",
    "You make my heart do the salsa 💃🌶️",
    "You're my favorite desktop shortcut 🖥️💖",
    "You're the crunch to my autumn walk 🍁💫",
    "You make my soul do the tango 💃❤️",
    "You're my favorite RAM upgrade 💻💕",
    "You're the fizz to my champagne 🥂✨",
    "You make my heart go disco ball 🪩💃"
    "You are my sunshine ☀️",
    "I love you more than chocolate 🍫😂",
    "You make my heart go boom 💥❤️",
    "You're my favorite person 💕",
    "Life is better with you 😍",
    "You're the apple of my eye 🍎😍",
    "My heart beats only for you 💓",
    "You're sweeter than candy 🍬💖",
    "You're my happily ever after 👑❤️",
    "You light up my world ✨💫",
    "You're my dream come true 🌈🌟",
    "My love for you is endless ♾️💕",
    "You're my favorite hello 👋❤️",
    "You make my soul smile 😊💫",
    "You're my perfect match 💑✨",
    "You're the melody to my heart 🎶❤️",
    "With you, every day is Valentine's 💝🌹",
    "You're my lucky charm 🍀💖",
    "You're the missing piece to my puzzle 🧩❤️",
    "You make my heart dance 💃🕺💓",
    "You're my forever and always 💍💕",
    "You're the reason I smile 😄❤️",
    "You're my favorite adventure 🗺️💘",
    "You're the best thing that ever happened to me 🎉💖",
    "You're my one in a million 🌟💕",
    "You make my world colorful 🎨🌈",
    "You're my safe place 🏠❤️",
    "You're the sweetest surprise 🎁💘",
    "You're my happy place 🏝️😊",
    "You're the answer to my prayers 🙏💖",
    "You make ordinary moments magical ✨💫",
    "You're my favorite notification 📱❤️",
    "You're the sparkle in my eyes ✨😍",
    "You're my personal sunshine 🌞💛",
    "You make my heart sing 🎤❤️",
    "You're my favorite chapter 📖💕",
    "You're the butter to my bread 🍞🧈😂",
    "You're my favorite thought 💭❤️",
    "You make my days brighter ☀️💖",
    "You're my heart's home 🏡💓",
    "You're my perfect cuddle buddy 🤗💕",
    "You're the best part of my day 📅❤️",
    "You make my worries disappear 🎈💫",
    "You're my favorite comfort food 🍲💖",
    "You're the twinkle in my star 🌟✨",
    "You make everything better 🌈💕",
    "You're my favorite distraction 😉❤️",
    "You're the beat to my heart 🥁💓",
    "You're my forever crush 💘😍",
    "You make life beautiful 🦋💖",
    "You're my favorite memory maker 📸💕",
    "You're the calm to my storm ⛈️🌈",
    "You make my dreams sweeter 💤✨",
    "You're my personal superhero 🦸‍♂️❤️",
    "You're the love of my life story 📚💘",
    "You make my soul sing 🎵💫",
    "You're my favorite notification 🔔💖",
    "You're the cherry on top 🍒💕",
    "You make my world go round 🎡❤️",
    "You're my happy pill 💊😂💖",
    "You're the sunshine after rain 🌦️☀️",
    "You make every moment magical 🪄✨",
    "You're my favorite human 👫💕",
    "You're the key to my heart 🗝️❤️",
    "You make my butterflies fly 🦋💫",
    "You're my forever Valentine 💝🌹",
    "You're the sweet in my life 🍯💖",
    "You make my heart skip a beat ⏭️💓",
    "You're my favorite blessing 🙌💕",
    "You're the warmth in my heart 🔥❤️",
    "You make every day special 🎊💫",
    "You're my personal happiness 😊💖",
    "You're the reason my heart smiles 😄💓",
    "You make my world perfect 🌎💕",
    "You're my favorite everything ❤️💫",
    "You're the love my heart sings 🎶💖",
    "You make my soul dance 💃🕺",
    "You're my dream team member 👫🌟",
    "You're the best decision I ever made ✅💕",
    "You make my heart feel home 🏡❤️",
    "You're my favorite reality 😍💫",
    "You're the reason I believe in love 💘💖",
    "You make my life complete ✅💕",
    "You're my heart's favorite song 🎵❤️",
    "You're the sweetest melody 🎶💖",
    "You make my days sparkle ✨💫",
    "You're my forever crush 💘😍",
    "You're the best part of waking up ☕💕",
    "You make my heart feel safe 🛡️❤️",
    "You're my favorite miracle ✨💖",
    "You're the love I always dreamed of 💭💕",
    "You make everything worthwhile 🌟❤️",
    "You're my heart's true home 🏠💖",
    "You're the sunshine of my life 🌞💕",
    "You make my world go 'wow' 😲❤️",
    "You're my favorite sweet dream 💤💖",
    "You're the answer to all my questions ❓💕",
    
]

    random_message = random.choice(messages)

    return render(request, 'funzone/message_generator.html', {
        'message': random_message
    })





def heart_game(request):
    return render(request, 'funzone/heart_game.html')