# Generated by Django 5.2.1 on 2026-02-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Confession',
        ),
    ]
